version: '3.8'

services:
  master:
    build:
      context: ./master
    networks:
      - worker-network

  slave:
    build:
      context: ./slave
    networks:
      - worker-network

networks:
  worker-network:
